services:
  api:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: sh -c "while ! pg_isready -h db -p 5432 -U bookuser; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookdatabase
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: mypassword

volumes:
  dev_db_data:
